name: "[BugReport] 游戏崩溃 / 错误行为"
description: 记录你遇到的与该模组相关的游戏崩溃、或错误的游戏行为逻辑
labels: [ "type: bug" ]
body:
    -   type: textarea
        attributes:
            label: Context
            description: "
                错误发生时你正在做什么？
                该问题是否能复现？
                若能更好地描述问题，你可以上传图片、录制视频来辅助描述你的问题。
            "
        validations:
            required: true

    -   type: textarea
        attributes:
            label: Context
            description: "
                你当前的 Minecraft 游戏版本是？(1.18.2/...)
                你当前的模组加载器是？ (Forge/Fabric/...)
                当前 TreasureSeas 的版本是？
            "
        validations:
            required: true

    -   type: input
        attributes:
            label: Crash Report
            description: "
            需要提供 crash-report 来分析错误原因
            该文件可以在你的 minecraft 目录下的 \"crash-reports\" 文件夹内找到
            请上传最新一个报告文件到 https://mclo.gs/ 然后在此处直接粘贴网址
            请不要直接粘贴所有报告内容到 issue 中，它实在是太长了。
            "
        validations:
            required: false

    -   type: markdown
        attributes:
            value: "谢谢你帮忙让模组变得更好～"
